README.md
dckr/Dockerfile
docker-compose.yml

```bash
docker-compose up -d
docker-compose exec soma firebase login --no-localhost
docker-compose exec soma firebase init functions
docker-compose exec npm run dev
```
が全て正常に動作することを確認してください。
close #8

Add#8/docker with firebase

---

components/Header.vue

humbergerbugfix

---

pages/articles/index.vue
store/index.js

implement vuex

---

docker-compose.yml

dockerhubのorganization化に合わせてimagenameを変えました。
close #4

change docker image

---

.circleci/config.yml
docker-compose.yml
package.json

Fix#16/no fix circleci lint

---

components/Header.vue
package-lock.json
pages/about/index.vue
pages/articles/index.vue
pages/auth/resetPassword.vue
pages/auth/signin.vue
pages/auth/signup.vue
pages/contact/index.vue
plugins/firebase.js
test/unit/components/Card.spec.js
test/unit/pages/about/index.spec.js
test/unit/pages/articles/_slug.spec.js
test/unit/pages/articles/index.spec.js
test/unit/pages/contact/index.spec.js

ログイン機能のベースを作成しました。
UIに関してはまだまだなので別issueで解決します。

Add#24/add login

---

pages/articles/index.vue

content-typeがarticleであるもののみ取ってくるようにしました。
close #29

Fix#29 : 空白のarticleが出るのを修正

---

components/Header.vue
components/WriterCard.vue
pages/about/index.vue
pages/articles/index.vue
pages/contact/index.vue
plugins/contentful.js
store/index.js
test/unit/pages/about/index.spec.js

WritersをAboutに追加
スペーサ機能をbannerからheaderそのものにつけ直し。
contentfulのクライアントを使い回しするように。

add#31 / Writer一覧追加

---

pages/articles/_slug.vue

記事ページに情報を追加しました。
関連する診療科とデータセットの情報です。
また。タイトルがスマホで表示したときに大きすぎるのでそこそこの大きさに調整しました。
まだ微妙な感じなのでコメントバシバシください

fix layouts of article page

---

pages/auth/signup.vue

登録ページにおけるalertの代わりに、対応する項目にtooltipが出るようにしました。
login等についても引き続き行います

登録ページのalertをTooltipにした

---

components/SearchForm.vue

changed searchform layout

---

components/Card.vue

changed card layout

---

pages/contact/index.vue

add contact

---

components/Card.vue
components/Header.vue
pages/articles/index.vue
pages/columns/_slug.vue
pages/columns/index.vue
store/column.js
store/model/Column.js
store/model/ColumnDetail.js
store/model/ColumnList.js
store/repository/ColumnRepository.js
store/repository/RepositoryFactory.js

コラム記事と論文記事を混ぜるのはちょっと難しかったので別ページに立てました。

add column page

---

components/WriterCard.vue
pages/about/index.vue

aboutページのレイアウト崩れ修正

---

pages/articles/_slug.vue

article detail design renewal

---

pages/articles/_slug.vue

データセットのテーブルの横幅修正

---

pages/columns/_slug.vue
store/column.js
store/repository/ColumnRepository.js

- storeの中にバグがあったので修正しました
- コラムの横幅が狭すぎたので広くしました

コラム記事の詳細ページのバグ修正

---

pages/articles/_slug.vue

 データセットのテーブルの横幅修正

---

components/ErrorAlert.vue
layouts/default.vue
pages/auth/signin.vue
store/error.js

Ajax時のエラーハンドリングを追加

---

pages/auth/changeEmail.vue
pages/mypage/index.vue

メールパスワードの更新を実装

---

components/loading.vue
nuxt.config.js

#41 add loading

---

components/ErrorAlert.vue
pages/articles/_slug.vue
plugins/contentful.js
store/error.js
store/model/ArticleDetail.js
store/repository/ArticleRepository.js

記事詳細ページに作成者、査読者とデータセットの有無を追記しました

---

components/SelectDepartment.vue
pages/articles/index.vue
pages/mypage/index.vue
store/article.js
store/model/Article.js
store/model/ArticleList.js
store/repository/ArticleRepository.js

診療科による検索を実装しました

---

components/WriterCard.vue
pages/about/index.vue

Fix#87/fix writer card

---

components/Card.vue
pages/articles/index.vue
pages/mypage/index.vue
store/model/Article.js

【#77に依存】popoverを追加

---

layouts/error.vue
pages/about/index.vue
pages/articles/_slug.vue
pages/articles/index.vue
pages/columns/_slug.vue
pages/columns/index.vue
pages/mypage/index.vue

- 任意のエラーメッセージ
- 500エラー
- 404エラー

SSRのエラーハンドリングを追加

---

pages/mypage/index.vue

ユーザーページのレイアウト崩れを修正

---

layouts/default.vue
pages/auth/resetPassword.vue
pages/auth/signin.vue

Fix#38/fix error pop

---

pages/articles/_slug.vue
pages/columns/_slug.vue

コラムページデザイン変更（本文を除く）

---

components/Card.vue
components/WriterCard.vue
firebase.json
functions/index.js

- functionsに関してマイページでエラーが出ていたので修正しました
- card幅を修正してcolumnとmypageで横長になるのを修正しました
- about画面をスマホで見たときに崩れるのを修正しました

リリース前の修正をしました

---

pages/columns/_slug.vue

コラムページのrich-textのレンダリングを変更しました

---

pages/columns/index.vue
pages/mypage/index.vue

デザイン　マイページ カードの横幅の修正

---

pages/articles/index.vue
pages/columns/index.vue
pages/contact/index.vue
pages/mypage/index.vue

ページタイトルとフッターの追加

---

components/SearchForm.vue
components/SelectDepartment.vue
pages/articles/index.vue
store/article.js
store/index.js
store/model/ArticleList.js

デザイン部分の修正は終わりました。　related #129

searchformのデザイン修正

---

components/Header.vue
functions/index.js
pages/sponsors/index.vue

Add sponsors
